### ISSUE TITLE
demo example input data?

### ISSUE THREAD

**Issue by keypointt** [dlwh/epic-demo#1]
Hi @dlwh thanks for the great work here, it's really useful for supporting multi-languages.

Since I'm just a beginner, could you please provide your example data set?

I'm trying to run examples at https://github.com/dlwh/epic-demo, I've tried some inputFiles as args passed, but it seems the data is not matching up.

So if you could provide the example input for the epic-demo examples, that will be greatly appreciated. Thank you very much :)

**Comment by gjgd** [comment]
I encountered the same problem.
Whilst digging through the code, I realised that the TextExtractor searches text **in HTML tags.**

So try giving it text inside html tags. Hope this can help someone
